version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - '3306'
    network_mode: 'host'
    volumes:
      - /var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql